import linksIntScroll from "./modules/links-scroll.js";
import scrollAnimation from "./modules/scroll-suave.js";
import tabNav from "./modules/tab-nav.js";
import accordionList from "./modules/accordion-list.js";
import modalLogin from "./modules/modal.js";
import toolTip from "./modules/tooltip.js";
import dropdownMenu from "./modules/dropdown-menu.js";
import menuMobile from "./modules/menu-mobile.js";
import animacaoNumeros from "./modules/animacao-num.js";
import funcionamento from "./modules/horario-func.js";
import initFetchBtc from "./modules/fetch-btc.js";
import { Slide, SlideNav } from "./modules/slide.js";

initFetchBtc();
funcionamento();
menuMobile();
toolTip();
modalLogin();
tabNav();
linksIntScroll();
accordionList();
scrollAnimation();
dropdownMenu();
animacaoNumeros();
const slide = new SlideNav(".slide", ".slide-wrapper");
slide.init();
slide.addCustomControl(".custom-controls");
